name = "LocalRegistry"
uuid = "46969c15-e807-419a-807f-3fa69f2ef89f"
repo = "git@github.com:minhcly95/JuliaPrivateRegistry.git"
description = "My private registry"

[packages]
a6206385-a85b-45a1-9870-e715cb6a9b8e = { name = "RubiksCore", path = "R/RubiksCore" }
