name = "Minhcly95Registry"
uuid = "46969c15-e807-419a-807f-3fa69f2ef89f"
repo = "https://github.com/minhcly95/JuliaRegistry.git"
description = "minhcly95's private registry for testing unregistered packages"

[packages]
a6206385-a85b-45a1-9870-e715cb6a9b8e = { name = "RubikCore", path = "R/RubikCore" }
